name: fetch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Submodule TSM
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

          pushd src/engine/tsm

          git fetch origin --prune
          git checkout main-src
          git pull origin main-src

          popd

          git add src/engine/tsm
          git commit -m "chore(tsm): bump submodule to TSM main-src"

      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true